ALTER TABLE "hero_sections"
  ADD COLUMN IF NOT EXISTS "badge_color" TEXT DEFAULT '#7F7FFF',
  ADD COLUMN IF NOT EXISTS "title_color" TEXT DEFAULT '#111827',
  ADD COLUMN IF NOT EXISTS "description_color" TEXT DEFAULT '#374151',
  ADD COLUMN IF NOT EXISTS "overlay_color" TEXT DEFAULT '#000000',
  ADD COLUMN IF NOT EXISTS "overlay_opacity" DECIMAL(3,2) DEFAULT 0.35,
  ADD COLUMN IF NOT EXISTS "button_color" TEXT DEFAULT '#7F7FFF',
  ADD COLUMN IF NOT EXISTS "button_text_color" TEXT DEFAULT '#FFFFFF';
